- hosts: builder
  roles:
    - openwisp.openwisp2-imagegenerator
  vars:
    basedir: /home/jenkins/workspace/nnxx-firmware
    openwisp2fw_ssl_lib: mbedtls
    openwisp2fw_source_dir: "{{ basedir }}/source"
    openwisp2fw_generator_dir: "{{ basedir }}/generator"
    openwisp2fw_bin_dir: /var/www/downloads.openwisp.org/nnxx-firmware/hotspot/
    openwisp2fw_source_targets:
        - system: ar71xx
          subtarget: generic
          profile: Default
        - system: x86
          subtarget: generic
          profile: Generic
        - system: ramips
          subtarget: mt7620
          profile: DEVICE_miwifi-mini
        - system: brcm2708
          subtarget: bcm2710
          profile: DEVICE_rpi-3
        - system: sunxi
          profile: DEVICE_sun7i-a20-lamobo-r1
        - system: ipq806x
          profile: Default
    openwisp2fw_source_feeds:
        - method: src-git
          name: openwisp
          location: https://github.com/openwisp/openwisp-config.git
          branch: master
        - method: src-git
          name: luciopenwisp
          location: https://github.com/openwisp/luci-openwisp.git
          branch: master
        - method: src-git
          name: packages
          location: https://github.com/openwrt/packages.git
          branch: lede-17.01
        - method: src-git
          name: luci
          location: https://github.com/openwrt/luci.git
          branch: lede-17.01
        - method: src-git
          name: targets
          location: https://github.com/openwrt/targets.git
          branch: master
        - method: src-git
          name: routing
          location: https://github.com/openwrt-routing/packages.git
          branch: lede-17.01
    # packages compiled during compilation step
    openwisp2fw_source_additional_packages:
        - wpad
        - iputils-ping
        - ip-full
        - wget
        - partx-utils
        - oonf-olsrd2
        - luci
        - luci-ssl
        - iputils-ping
        - ip-full
        - iwinfo
        - iperf3
        - ipip
        - kmod-fs-ext4
        - kmod-fs-vfat
        - kmod-usb-storage
        - kmod-usb-storage-extras
        - kmod-ipip
        # mt7620
        - kmod-usb-ohci
        - kmod-usb2
        - kmod-mt76
        # brcm2708
        - kmod-brcmfmac
        - brcmfmac-firmware-43430
        # sunxi
        - kmod-ata-core
        - kmod-ata-sunxi
        # olsrd1 specifc, used by Palermo
        - olsrd
        - olsrd-mod-nameservice
        - olsrd-mod-arprefresh
        - olsrd-mod-dyn-gw
        - olsrd-mod-txtinfo
        - olsrd-mod-jsoninfo
        - luci-lib-json
        - luci-app-olsr
        # packages for hotspot
        - nodogsplash2
        - kmod-ifb
        - tc
        - kmod-sched
        - kmod-ath9k-htc
        - sqm-scripts
#        - acme
    # other OpenWRT/LEDE configurations
    openwisp2fw_source_other_configs:
        # busybox
        - CONFIG_BUSYBOX_CUSTOM=y
        - CONFIG_BUSYBOX_CONFIG_FEATURE_EDITING_SAVEHISTORY=y
        - CONFIG_BUSYBOX_CONFIG_FEATURE_EDITING_SAVE_ON_EXIT=y
        - CONFIG_BUSYBOX_CONFIG_FEATURE_REVERSE_SEARCH=y
        - CONFIG_BUSYBOX_CONFIG_FEATURE_VI_UNDO=y
        - CONFIG_BUSYBOX_CONFIG_WATCH=y
        - CONFIG_BUSYBOX_CONFIG_WHOIS=y
        # olsrd2
        - CONFIG_OONF_NHDP_AUTOLL4=y
        - CONFIG_OONF_OLSRV2_LAN_IMPORT=y
        # workaround to avoid conflicts between wpad and wpad-mini
        - "# CONFIG_PACKAGE_wpad-mini is not set"
    # packages passed to "PACKAGES" flag of image builder (in the image building step)
    openwisp2fw_default_packages:
        - -ppp
        - -ppp-mod-pppoe
        - -wpad-mini
        - wpad
        - uhttpd
        - uhttpd-mod-ubus
        - openvpn-{{ openwisp2fw_ssl_lib }}
        - openwisp-config-{{ openwisp2fw_ssl_lib }}
    # packages used in the full flavour
    nnxx_full_packages:
        - iputils-ping
        - ip-full
        - wget
        - partx-utils
        - iputils-ping
        - ip-full
        - iwinfo
        - iperf3
        - ipip
        - kmod-fs-ext4
        - kmod-fs-vfat
        - kmod-usb-storage
        - kmod-usb-storage-extras
        - kmod-ipip
        - libustream-{{ openwisp2fw_ssl_lib }}
        - px5g
        - luci-ssl
     # packages used in the nossl flavour
    nnxx_nossl_packages:
        - luci
    olsrd2_packages:
        - oonf-olsrd2
    olsrd1_packages:
        - olsrd
        - olsrd-mod-nameservice
        - olsrd-mod-arprefresh
        - olsrd-mod-dyn-gw
        - olsrd-mod-txtinfo
        - olsrd-mod-jsoninfo
        - luci-lib-json
        - luci-app-olsr
    # packages used in the hotspot
    nnxx_hotspot_packages:
        - nodogsplash2
#        - luci-app-sqm
        - sqm-scripts
        - kmod-ifb
        - tc
        - kmod-sched
        - kmod-ath9k-htc
#        - acme
    # packages used in flavours
    full_olsrd2_packages: "{{ openwisp2fw_default_packages + nnxx_full_packages + olsrd2_packages }}"
    full_olsrd1_packages: "{{ openwisp2fw_default_packages + nnxx_full_packages + olsrd1_packages + olsrd2_packages }}"
    nossl_olsrd1_packages: "{{ openwisp2fw_default_packages + nnxx_nossl_packages + olsrd1_packages + olsrd2_packages }}"
    full_olsrd2_hotspot_packages: "{{ openwisp2fw_default_packages + nnxx_full_packages + olsrd2_packages + nnxx_hotspot_packages }}" 
   # definition of available flavours
    openwisp2fw_image_flavours:
        hotspot_olsrd2:
          sunxi:
            packages: "{{ full_olsrd2_hotspot_packages + ['-kmod-eeprom-sunxi'] }}"
          ar71xx:
            packages: "{{ full_olsrd2_hotspot_packages + ['-kmod-ath9k-htc'] }}"
          x86:
            packages: "{{ full_olsrd2_hotspot_packages }}"
          ramips:
            packages: "{{ full_olsrd2_hotspot_packages + ['-kmod-ath9k-htci'] }}"
          brcm2708:
            packages: "{{ full_olsrd2_hotspot_packages + ['-kmod-ath9k-htci'] }}"
          ipq806x:
            packages: "{{ full_olsrd2_hotspot_packages + ['-kmod-ath9k-htci'] }}"
    # definition of organizations
    default_openwisp2_url: https://openwisp.nnxx.ninux.org
    openwisp2fw_organizations:
        - name: defaults
          flavours:
            - hotspot_olsrd2
          openwisp:
            url: "{{ default_openwisp2_url }}"
            shared_secret: Secretn1nuxB4s
            unmanaged: "{{ openwisp2fw_default_unmanaged }}"
        - name: basilicata
          flavours:
            - hotspot_olsrd2
          openwisp:
            url: "{{ default_openwisp2_url }}"
            shared_secret: Secretn1nuxB4s
            unmanaged: "{{ openwisp2fw_default_unmanaged }}"
        - name: palermo
          flavours:
            - hotspot_olsrd2
          openwisp:
            url: "{{ default_openwisp2_url }}"
            shared_secret: Secretn1nuxB4s
            unmanaged: "{{ openwisp2fw_default_unmanaged }}"


